In [5]:
import pandas as pd

In [6]:
data_file = 'data/RSM-Ebner-Stolz-Data.xlsx'

# Replace 'output.csv' with the name you want for your CSV file.
csv_file = 'output.csv'

df = pd.read_excel(data_file)
df.to_csv(csv_file, index=False)
df

,Scenario: \n,"You are data analysts in the field of financial auditing. Your auditor colleagues are right in the middle of the busy season, reviewing annual and consolidated financial statements. \n\nOne afternoon, Mrs. Schulte approaches you for assistance. She is currently in the process of examining her client's balance sheet, specifically focusing on the miscellaneous liabilities. Among these Other Payables, there are four accounts (#13274, #15689, #26589, #32197) with various transactions. Mrs. Schulte is only interested in reviewing the transactions that are relevant as of the balance sheet date. Since the client does not maintain an open items list, Mrs. Schulte needs to identify the open items within the account statements. Given your reputation as data and algorithm experts, she asks if you could help her.",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Task:,"Using a tool and the language of your choice, ...",NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Procedure:,"For each account statement, a separate sheet i...",NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Bilanz,NaN,NaN,NaN,NaN,NaN
6,NaN,Konto,NaN,Bericht,Bericht Vorjahr,Abweichungen Betrag,Abweichungen %
7,NaN,3.600.110 Sonstige Verbindlichkeiten,NaN,-93337.38,-76681.95,-16655.43,0.217201
8,NaN,13274,Sonstige Verbindlichkeiten 01,-2087.32,-1060.78,-1026.54,0.967722
9,NaN,15689,Sonstige Verbindlichkeiten 02,-9.57,-5926.41,5916.84,-0.998385
10,NaN,26589,Sonstige Verbindlichkeiten 03,-34103.91,-25984.1,-8119.81,0.312491
11,NaN,32197,Sonstige Verbindlichkeiten 04,-59233.47,-50697.85,-8535.62,0.168363
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,-93337.38,-76681.95,-16655.43,0.217201